FROM frolvlad/alpine-miniconda3:python3.7
# FROM python:3.8-alpine

# RMR setup
RUN mkdir -p /opt/route/

# sdl uses hiredis which needs gcc
RUN apk update && apk add gcc musl-dev

# copy rmr libraries from builder image in lieu of an Alpine package
COPY --from=nexus3.o-ran-sc.org:10002/o-ran-sc/bldr-alpine3-rmr:4.0.5 /usr/local/lib64/librmr* /usr/local/lib64/

# Upgrade pip, install tox
RUN pip install --upgrade pip && pip install tox
RUN apk update && apk add gcc musl-dev

# copies
COPY setup.py tox.ini LICENSE.txt /tmp/
RUN pip install /tmp
COPY src/ /tmp/src
COPY tests/ /tmp/tests
# Run the unit tests
WORKDIR /tmp 
RUN PYTHONPATH=/tmp/src:/usr/lib/python3.7/site-packages/:$PYTHONPATH tox -e code,flake8